name: Scanning for Secrets
run-name: ${{ github.actor }} is scanning for secrets

# Controls when the action will run
on:
  push:
    branches:
      - main
  pull_request:

# Control the permissions for the workflow
# We default to no permissions so jobs have to explicitly set permissions they need. This is a secure default.
permissions: {}

# Jobs
jobs:
  TruffleHog:
    name: Secret Scanning
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: 📁 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
          fetch-depth: 0
          
      - name: 🕵🏽‍♂️ TruffleHog OSS
        uses: trufflesecurity/trufflehog@6bd2d14f7a4bc1e569fa3550efa7ec632a4fa67b
        with:
          extra_args: --results=verified,unknown